---
- name: Install Development Tools
  hosts: servers
  become: true
  vars:
    redis_port: 6379
    redis_databases: 1

  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Skype
      shell: " snap install skype --classic"

    - name: loop some package
      ansible.builtin.apt:
       name: "{{ item }}"
       state: present
      with_items:
         - curl
         - gnupg
         - software-properties-common

    - name: Install Visual Studio Code
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
      notify: Update package cache

    - name: Install MongoDB
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.4.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
        state: present
      notify: Update package cache

    - name: Install Node.js and npm
      shell: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -"

    - name: Installing Redis
      apt: pkg=redis-server state=latest

    - name: Ensure Redis is started
      service: name=redis-server state=started enabled=yes
    - name: update
      ansible.builtin.apt:
        update_cache: yes

    - name:
      shell: "sudo snap install code --classic"
