---
- name: Playbook to install PHP versions
  hosts: servers
  become: yes

  vars_prompt:
    name: PHP_version
    prompt: "Enter the PHP version to install"
    private: no

  tasks:
  - name: update cachec and remove previous PHP
    apt:
      update_cache: yes
      name: php*
      state: absent
  - name: adding ppa
    apt_repository:
      repo: ppa:ondrej/php
      state: present
  - name: update cache
    apt:
      update_cache: yes
  - name: install php
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - php{{PHP_version}}
      - php{{PHP_version}}-common
      - php{{PHP_version}}-cli
      - php{{PHP_version}}-fpm
      - php{{PHP_version}}-zip
      - php{{PHP_version}}-mysql
      - php{{PHP_version}}-mbstring
      - php{{PHP_version}}-curl
      - php{{PHP_version}}-mysqli
