---
- name: ReactJS Playbook
  hosts: servers
  become: true

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Install Git CLI
      ansible.builtin.apt:
        name: git-core
        state: present

    - name: Install Visual Studio Code
      ansible.builtin.shell:
        cmd: "sudo snap install --classic code"


    - name: Install necessary build tools for some npm packages
      ansible.builtin.apt:
        name: build-essential
        state: present

    - name: Upgrade npm to the latest version
      ansible.builtin.shell:
        cmd: "sudo npm install -g npm"

    - name: Clean up apt cache
      ansible.builtin.apt:
        autoclean: yes
